"""empty message

Revision ID: f72f40dad9a8
Revises: 
Create Date: 2022-11-11 11:44:07.337499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72f40dad9a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('room_number', sa.String(length=3), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('economy', 'comfort', 'comfortplus', 'luxe', name='type'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('photo_url', sa.String(length=120), nullable=True),
    sa.Column('bed_n', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('room_number')
    )
    op.create_table('reservation',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('id_room', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['id_room'], ['room.room_number'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.drop_index('admin_id', table_name='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('admin_id', 'admin', ['admin_id'], unique=False)
    op.drop_table('reservation')
    op.drop_table('room')
    # ### end Alembic commands ###
